Added game mechansics (shot, hit, miss)
falker47/Battleship_APIs pull request #2
Opened 2023-04-20 17:51 UTC by RedGuardiaN7

2023-04-20 18:28 UTC, LoggiExp commented on Controllers/PlayersController.cs
> +            }
remove spaces

2023-04-20 18:29 UTC, LoggiExp commented on Controllers/PlayersController.cs
> +            }
remove spaces

2023-04-20 18:52 UTC, LoggiExp commented on Controllers/PlayersController.cs
> +
io rimuoverei gli spazi tra le righe in eccesso

2023-04-20 18:56 UTC, LoggiExp commented on Controllers/PlayersController.cs
> +
e gestirei l'input con un oggetto personalizzato, senza inserirlo nell'url dell'API

2023-04-20 19:37 UTC, LoggiExp requested changes

2023-04-20 19:37 UTC, LoggiExp commented on Controllers/PlayersController.cs
> +            if (attackingPlayer != null && xAxis < 31 && yAxis < 31)
attackingPlayer è sicuramente non null, lo controlli in GetObjectPlayer

2023-04-20 19:37 UTC, LoggiExp commented on Controllers/PlayersController.cs
> +            if (attackingPlayer != null && xAxis < 31 && yAxis < 31)
e se x e y sono negative?

2023-04-20 19:37 UTC, LoggiExp commented on Controllers/PlayersController.cs
> +                    if (attackedCell != null && attackedCell.ShipId != null)
se x e y sono controllate prima, la cella esiste per forza.
ma se non esiste cosa succede?

2023-04-20 19:37 UTC, LoggiExp commented on Controllers/PlayersController.cs
> +
se le cordinate sono inesistenti cosa succede?
manca else statement

2023-04-20 19:37 UTC, LoggiExp commented on Controllers/PlayersController.cs
> +            cellToEdit.State = 1;
cambiare stato a 3

2023-04-20 19:37 UTC, LoggiExp commented on Controllers/PlayersController.cs
> +
manca l'udate dello stato delle celle di chi viene attaccato, in modo da vedere dove si è stati colpiti, anche acqua

2023-04-20 19:37 UTC, LoggiExp commented on Controllers/PlayersController.cs
> +                        ResponseMessage += $"The ship of {attackedPlayer.Name} has been missed!;";
plurale, ci sono più navi

2023-04-20 19:37 UTC, LoggiExp commented on Controllers/PlayersController.cs
> +            cellToEdit.State = 3;
state = 2

2023-04-20 19:37 UTC, LoggiExp commented on Controllers/PlayersController.cs
> +            attackedCell.State = 3;
state = 2

2023-04-20 19:37 UTC, LoggiExp commented on Controllers/PlayersController.cs
> +        }
manca la gestione dei punti, qui o dove viene chiamata

2023-04-20 19:37 UTC, LoggiExp commented on Controllers/PlayersController.cs
> +            }
anche qui toglierei gli spazi di troppo, gusto personale sempre, perchè faccio fatica a leggere il codice così

2023-04-21 07:40 UTC, LoggiExp commented on Controllers/PlayersController.cs
> +            }
penso sia giusto così

2023-04-21 07:40 UTC, LoggiExp commented on Controllers/PlayersController.cs
> +            }
penso sia giusto così

2023-04-21 09:46 UTC, RedGuardiaN7 reviewed
Done!

2023-04-21 09:46 UTC, RedGuardiaN7 commented on Controllers/PlayersController.cs
> +            if (attackingPlayer != null && xAxis < 31 && yAxis < 31)
Done

2023-04-21 09:46 UTC, RedGuardiaN7 commented on Controllers/PlayersController.cs
> +                    if (attackedCell != null && attackedCell.ShipId != null)
Done

2023-04-21 09:46 UTC, RedGuardiaN7 commented on Controllers/PlayersController.cs
> +                        ResponseMessage += $"The ship of {attackedPlayer.Name} has been missed!;";
Done

2023-04-21 09:46 UTC, RedGuardiaN7 commented on Controllers/PlayersController.cs
> +
Done

2023-04-21 09:46 UTC, RedGuardiaN7 commented on Controllers/PlayersController.cs
> +            cellToEdit.State = 1;
Done

2023-04-21 09:46 UTC, RedGuardiaN7 commented on Controllers/PlayersController.cs
> +
Da pensare

2023-04-21 09:46 UTC, RedGuardiaN7 commented on Controllers/PlayersController.cs
> +            cellToEdit.State = 3;
Done

2023-04-21 09:46 UTC, RedGuardiaN7 commented on Controllers/PlayersController.cs
> +            attackedCell.State = 3;
Done

2023-04-21 09:46 UTC, RedGuardiaN7 commented on Controllers/PlayersController.cs
> +
Done

2023-04-21 09:46 UTC, RedGuardiaN7 commented on Controllers/PlayersController.cs
> +            }
Done

2023-04-21 09:46 UTC, RedGuardiaN7 commented on Controllers/PlayersController.cs
> +        }
Done

2023-04-21 11:41 UTC, LoggiExp approved these changes

2023-04-21 11:41 UTC, merged